---
dist: focal
language: c
sudo: required

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

before_install:
  - sudo -H pip3 install ansible

install:
  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; echo 'deprecation_warnings=False'; } >> ansible.cfg"

script:
  # Test 0: Check the roles syntax.
  - "ANSIBLE_FORCE_COLOR=1 ansible-playbook -i tests/inventory tests/test_default.yml --syntax-check"

  # Test 1: Run the role
  - "ANSIBLE_FORCE_COLOR=1 ansible-playbook -i tests/inventory tests/test_default.yml --connection=local --become -v"

  # Test 2: Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/test_default.yml --connection=local --become | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Test 3: Check we can set arbitrary configuration options
  - >
    ANSIBLE_FORCE_COLOR=1 ansible-playbook -i tests/inventory tests/test_set_common.yml --connection=local --become -v
    && (echo 'Common variables test: pass' && exit 0)
    || (echo 'Common variables test: fail' && exit 1)
